### ISSUE TITLE
False quantity and unit of AbsoluteAcceleration sensor's output

### ISSUE THREAD

**Issue by olivleno** [dzimmer/PlanarMechanics#138]
seems like there is a copy&paste bug here as it should refer to acceleration instead of velocity in the quantity and the comment.
```
model AbsoluteAcceleration
  "Measure absolute acceleration vector of origin of frame connector"
  extends Internal.PartialAbsoluteSensor;
  Modelica.Blocks.Interfaces.RealOutput a[3](each final quantity="Velocity", each final 
            unit =                                                                    "m/s2")
    "Absolute velocity vector resolved in frame defined by resolveInFrame"

```

**Comment by tobolar** [comment]
Closed by commit c47861376b6495e41a59011ac59072b1695305c3.

**Comment by tobolar** [comment]
I have realized my changes to units and quantities are completely wrong since the output vectors are a combination of position and rotation. Consequently, all units and quantities shall be removed from all position, velocity and acceleration sensors.
For the next major version, the output vectors shall even be renamed to omit any doubt, e.g.
- `AbsolutePosition.r` -> `AbsolutePosition.r_phi`

**Comment by olivleno** [comment]
Yes, that is true. I recently stumbled over this inconsistency, when I had to look up the implementation to understand whether acc[3] is the planar angular acceleration or a 3D linear acceleration.
An alternative approach could be to define a dedicated record type.
