### ISSUE TITLE
Why Frames have **scalar** Position and Force?

### ISSUE THREAD

**Issue by dariomangoni** [dzimmer/PlanarMechanics#145]
Is there a reason why position and force members of **Interfaces.Frame** are given as scalar?
This forces any other component to manually handle these components by assembling a vector every time.

**Comment by tobolar** [comment]
I suppose it's more intuitive to adress those coordinates like `x` and `y`, rather then `r[1]` and `r[2]`, resp. And similarly to forces.
@dzimmer Please comment.

**Comment by dariomangoni** [comment]
I personally appreciate more the indexed version `r[1]` instead of `rx` mostly because:

- you cannot directly make vectorial operations with split scalar `rx` and `ry`
- other space vectors are not split in x and y (e.g. direction of *Joint.Prismatic*)
- declaring `Real r[2]` requires one line instead of two like in `Real rx`, `Real ry`
- the vectorial notation is convenient also for teaching, as transition to 3D space
- the Modelica Standard Library uses indexed notations

**Comment by dzimmer** [comment]
This originates from the didactic legacy of the library. Since students
learned to deal with arrays on the way, I made them not part of the
connector

When transforming the library, I asked around our users whether this an
issue and whether we should change it to an array.
However everyone was fine with the x,y solution and did not see an issue
with converting into an array when needed.

So it was kept this way.

tobolar <notifications@github.com> schrieb am Di., 1. Okt. 2019, 10:35:

**Comment by dariomangoni** [comment]
Ok, I understand.

Anyway, thanks for the interesting library. It will surely come in handy!
