### ISSUE TITLE
Damping force has incorrect dependency

### ISSUE THREAD

**Issue by vengelson** [dzimmer/PlanarMechanics#183]
SpringDamper between frames A and B in Planar library is actually
a combination of two springs AC(x direction) and CB(y direction).
Two nonzero damping forces are created when |AB| remains constant but |AC| and |CB| change.
Typically, this happens for a single pendulum.
However, if C==A or C==B this SpringDamper works a normal spring-and-damper hanging freely anywhere in 2D. 
My proposal is that the derivative of distance |AB| is computed, 
the damping force is computed only once, 
and only after that it is split to x,y-components.

**Comment by tobolar** [comment]
> However, if C==A or C==B this SpringDamper works a normal spring-and-damper hanging freely anywhere in 2D.

@vengelson Can you provide an example for this?

I suppose in that case either of the following happens:
- `s_relx = v_relx = 0` => `f_x = 0` or
- `s_rely = v_rely = 0` => `f_y = 0` .

Additionally, and this is what probably happens in your case, 
- `phi_rel = frame_b.phi - frame_a.phi = 0`. (Compare `frame_b.phi` and `frame_a.phi` signals.)

Anyway, either `f_x` or `f_y` shall still be non-zero.

P.S We talk about `PlanarMechanics.Parts.SpringDamper`, right?

**Comment by tobolar** [comment]
What you do in your model is a definition of a point-to-point spring/damper. And it is really not comparable to `PlanarMechanics.Parts.SpringDamper`, see my comment https://github.com/dzimmer/PlanarMechanics/issues/67#issuecomment-78449735.

I have extended your example `DualSpringProblem.DualPlanarPendulum` by a third pendulum model -  see below. The behavior of `body3`and `body2`is very similar now. The only difference is due to a missing "rxf" ("r" cross "f") in your model (i.e. you define in `SpringDamperWithLineForce` that `frame_a.t = frame_b.t = 0`). The same behavior with pendulum 3 can be reached, when setting `body3.I` very small. Then, "rxf" plays nearly no role.

[DualSpringProblem.zip](https://github.com/dzimmer/PlanarMechanics/files/11542340/DualSpringProblem.zip)

Concluding, I see no need to change the model now.
