### ISSUE TITLE
PlanarWorld model contains Visualizers.Advanced.CoordinateSystem which contains outer planarWorld

### ISSUE THREAD

**Issue by adrpo** [dzimmer/PlanarMechanics#80]
When you add inner PlanarWorld to a model it will contain an outer to itself which as far as I can tell is not valid Modelica. Do you really need coordinateSystem inside PlanarWorld?
It doesn't seem to be used anywhere (I searched for planarWorld.coordinateSystem).

I guess Dymola removes everything that is not used and that's why it can handle outer 
inside inner but if you try to use coordinateSystem from planarWorld it would probably 
complain.

**Comment by adrpo** [comment]
I now added a Modelica ticket about this:
https://trac.modelica.org/Modelica/ticket/1671
to find out if is legal or not to have outer inside inner.

**Comment by tobolar** [comment]
I don't know if this is legal in Modelica.
The idea is to simply have a visualizer for a coordinate system similar to any other visualization element. In such case, any advanced visualizer has outer planarWorld (or world in case of Modelica Multibody) and it can be used anywhere in the Modelica model. The animation is then dependent on the planarWorld.enableAnimation parameter which makes it easy to disable complete animation. 
Using coordinateSystem instance in PlanarWorld makes it easy to handle the visualization at once and to omit unnecessary visualization parameters.
I wonder what will be the answear from Modelica Association.

**Comment by tobolar** [comment]
Since the recomendation of Modelica association is rather to omit recursive instances (see ticket above), possible solution could be to define new CoordinateSystem visualizer within PlanarMechanics.Visualizers.*Intern* which has NO outer planarWorld. This element should be used for visualization of coordinate system within PlanarMechanics.PlanarWorld. For other purposes there still will be the visualizer PlanarMechanics.Visualizers.Advanced.CoordinateSystem which extends from internal CoordinateSystem and has outer PlanarWorld.
Is this acceptable solution?

**Comment by adrpo** [comment]
I think this should work fine.

**Comment by adrpo** [comment]
Unfortunately the fix does not work as PlanarMechanics.Visualizers.Intern.CoordinateSystem contains Advanced.Arrow which contains outer planarWorld again.

**Comment by tobolar** [comment]
I hope this is an acceptable solution...

**Comment by adrpo** [comment]
I'll update the library and re-run our tests and let you know. Thanks!

**Comment by adrpo** [comment]
It works fine now. 25/25 example simulate. Thanks a lot!
